version: '3'

volumes:
  root:

networks:
  app-network:
    name: rest-service-network
    driver: bridge


services:
  postgres:
    container_name: nodejs2022q2-service_postgres
    image: nodejs2022q2-service_postgres
    build: 
      dockerfile: ./database/Dockerfile
      context: .
    restart: always
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - app-network
    volumes:
      - root:/var/lib/postgresql/data

  node:
    container_name: nodejs2022q2-service_node
    image: nodejs2022q2-service_node
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    restart: always
    volumes:
      - .:/src
      - /node_modules
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-network
    depends_on:
      - postgres